// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdg9oARU9mOja5xMfAUuyllFdN402hYXc',
    appId: '1:77553642458:web:5142ee90a8f15e29a2aee3',
    messagingSenderId: '77553642458',
    projectId: 'svs1-6478f',
    authDomain: 'svs1-6478f.firebaseapp.com',
    storageBucket: 'svs1-6478f.appspot.com',
    measurementId: 'G-1S3N0JTKLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXCv8Lc6NKLIqPMCsSi1iyVaaZHo7RXkI',
    appId: '1:77553642458:android:bb28841056728498a2aee3',
    messagingSenderId: '77553642458',
    projectId: 'svs1-6478f',
    storageBucket: 'svs1-6478f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkBCvnsaBVpk9UW1GSYwY07hQPOCfh_Ac',
    appId: '1:77553642458:ios:53fe7e23a2e3b9a8a2aee3',
    messagingSenderId: '77553642458',
    projectId: 'svs1-6478f',
    storageBucket: 'svs1-6478f.appspot.com',
    iosClientId: '77553642458-eav15du2q4qca6o22q3q5f1o566j78sj.apps.googleusercontent.com',
    iosBundleId: 'com.example.svs',
  );
}
